### ISSUE TITLE
"Cannot find a definition for job named build" error calling workflow: 'build' when Implementing CircleCI "Trigger Build" webhook, 

### ISSUE THREAD

**Issue by AlexandraKlein** [contentful-labs/continous-delivery-environments-example#58]
When configuring CircleCI Trigger Build webhook via Contentful Dashboard at `/settings/webhooks`, job fails as it requires a job that wraps all jobs called `build`. Is there no way to configure this webhook to trigger all jobs in `.circleci/config.yaml`? We'd prefer to keep our jobs separate.

<img width="546" alt="Screen Shot 2021-02-09 at 8 09 37 AM" src="https://user-images.githubusercontent.com/6663760/107392256-5651fe80-6aae-11eb-9f4a-15217742e9aa.png">

**Comment by AlexandraKlein** [comment]
![Uploading Screen Shot 2021-02-09 at 8.09.37 AM.png…]()

**Comment by Shy** [comment]
Hey @AlexandraKlein this repo exists as a example. I expect you'd need to modify it to meet your needs so please feel free to adjust or change it as nessesary. 

In this example I don't actually use a webhook from Contentful to fire off a build, I end up using a push to GitHub to trigger a content migration. The logic being that if the content model is changing, the code should have also changed at the same time. Specifically using a contentful webhook to trigger a build seems like a bad pattern to me because you can't guarantee that code deployed is ready to handle whatever content model changes that you'd be sending up. 

In terms of getting a webhook to trigger a job I'd encourage you to take a look at the circle docs. They have support for running jobs via and API (https://circleci.com/docs/2.0/api-job-trigger/). You could set up a lambda function that is called by a webhook on Contentful and fires off an API call to circleCI trigger whatever jobs you need if that's appropriate.

**Comment by AlexandraKlein** [comment]
Hi @Shy,

I opened up an issue with Contentful Support and they encouraged me to open an issue here.

My problem is with the CircleCI Build webhook template in the Contentful Dashboard (/settings/webhooks).  It does not seem to allow me to set which jobs (all jobs?) I'd like to run from my config.yaml when that webhook is triggered. I only get the error `Cannot find a definition for job named build`, which tells me that webhook is looking for a job named `build` by default. I do not have a job named build. I have many jobs. And I'd like them all to be triggered, as is needed to deploy my site. Is there any way to tell Contentful which jobs to run? Or must a wrap my "jobs" in a job called `build` for this to execute? If so, that seems like an oversight on Contentful's part. If you don't know the answer to this, do you think you could connect me with someone that does? Perhaps someone on the webhooks team?

Below you'll find the screenshot of the CTA for the Trigger Build CircleCI template:

<img width="357" alt="Screen Shot 2021-02-09 at 1 28 54 PM" src="https://user-images.githubusercontent.com/6663760/107431064-cd04f100-6ada-11eb-955e-1839fba9edd9.png">

**Comment by Shy** [comment]
@AlexandraKlein I understand now. It looks like support pointed you to the wrong place. This repo and our circleci webhook template are totally different things. I pinged support to let them know and they've reached out to our dev team and will get back to you in a bit.  

In the interim, you can create custom webhooks (add a webhook above the template section) that don't use the templates at all. You can customize those to whatever your needs are. You can also modify the payload of the template webhook in the webhook settings after it's created. I'm not sure if changing the payload or building the webhook from scratch will be enough to let you specific which jobs it would need to run though. I haven't used circle ci's webhook functions before so I'd need to read there docs to find out.

**Comment by AlexandraKlein** [comment]
Thanks, @Shy ! Yeah, unfortunately the add webhook feature that doesn't use a template still does not have the option to specify job names from the config.yaml. I really appreciate you looking at this!

**Comment by AlexandraKlein** [comment]
#70329 is my Contentful Support request number. (https://support.contentful.com/hc/requests/70329)
