### ISSUE TITLE
Script creation of the new environment

### ISSUE THREAD

**Issue by marcoborsoi** [contentful-labs/continous-delivery-environments-example#59]
Hello @Shy @stefanjudis !

Thank you very much for this example and the detailed article https://www.contentful.com/developers/docs/tutorials/general/continuous-integration-with-circleci/! It's really helpful!

Can you provide some clarification about the step where we create the new environment.
The article says "Then, a new environment that’s a copy of master is created and polled until we received confirmation that it exists.", but when looking on /scripts/migrate.js:60 (https://github.com/contentful-labs/continous-delivery-environments-example/blob/548ad2b5c81098c8b38e43d03b964382f4462a0a/scripts/migrate.js#L60), it seems that a new environment is created, but not cloned from any other environment.

```
environment = await space.createEnvironmentWithId(ENVIRONMENT_ID, {
  name: ENVIRONMENT_ID,
});
```

I took a look at the Contentful Management API docs and I found that there is a third argument that needs to be provided when cloning an environment. Can you please confirm?

```
client.getSpace('<space_id>')
 .then((space) => space.createEnvironmentWithId('<custom-id>', { name: 'Staging'}, 'master'))
 .then((environment) => console.log(environment))
 .catch(console.error)
```

On that, should we pass ENVIRONMENT_INPUT as the missing argument?

Maybe I'm missing something. Can you provide me some guidance on that please?

Thank you!

**Comment by Shy** [comment]
Hey @marcoborsoi. That is a great question. Looking at this example I should have set it using the createEnvironment function rather than createEnvironmentWithId. It might be that at the time the function fell back to master if it didn't have an ID included, or it could have just been a bad choice on my part when I set this repo up.

The intention I had was the we should always be creating Environment based on the master ENV though. We'll always want to run migrations against whatever the most current master is at any given moment. You can explicitly call it out as you are in your solution or just switch to using createEnvironment() and it should work.

**Comment by marcoborsoi** [comment]
Hi @Shy. Ok, got it! ;)

Thank you so much!
